version: '3.1'

volumes:
  pg_goWithTomato:

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=GoWithTomato_db
    volumes: #
      - pg_goWithTomato:/var/lib/postgresql/data

    ports:
      - "0.0.0.0:5433:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      db.url: 'jdbc:postgresql://db:5432/GoWithTomato_db'